- src/moscot/problems/base/_mixins.py
- src/moscot/problems/space/_mixins.py
- src/moscot/solvers/_output.py
- tests/analysis_mixins/test_base_analysis.py
No longer takes `forward` as an argument
> Simplify linear operator

- src/moscot/backends/ott/_solver.py
- tests/backends/ott/test_backend.py
- tests/problems/conftest.py
Related to https://github.com/ott-jax/ott/pull/192
> Explicitly jit the solvers

- src/moscot/backends/ott/__init__.py
- src/moscot/backends/ott/_solver.py
- src/moscot/problems/base/_base_problem.py
- src/moscot/problems/generic/__init__.py
- src/moscot/problems/generic/_generic.py
- src/moscot/solvers/_base_solver.py
- tests/backends/ott/test_backend.py
- tests/problems/base/test_general_problem.py
- tests/problems/generic/test_fgw_problem.py
- tests/problems/generic/test_gw_problem.py
- tests/problems/space/test_mapping_problem.py
- tox.ini
> Remove `FGWSolver`

- src/moscot/datasets/_datasets.py
> [ci skip] Update `moscot.datasets.tedsim` docstring

- src/moscot/datasets.py
> Add `force_download` option to `moscot.datasets`

- src/moscot/_types.py
- src/moscot/problems/_utils.py
- src/moscot/problems/generic/_generic.py
- src/moscot/problems/space/_alignment.py
- src/moscot/problems/space/_mapping.py
- src/moscot/problems/spatiotemporal/_spatio_temporal.py
- src/moscot/problems/time/_lineage.py
- tests/problems/generic/test_fgw_problem.py
- tests/problems/generic/test_gw_problem.py
> introduce cost_kwargs_t

- src/moscot/base/output.py
- tests/solvers/test_base_solver.py
Encountered in https://github.com/theislab/cellrank/pull/1044
> Fix sparsification for `jax` arrays

- src/moscot/base/problems/compound_problem.py
- src/moscot/base/problems/problem.py
- src/moscot/problems/space/_alignment.py
- src/moscot/problems/space/_mapping.py
- tests/problems/space/test_alignment_problem.py
- tests/problems/space/test_mapping_problem.py
- tests/problems/space/test_mixins.py
> add spatial normalization

- src/moscot/datasets.py
specifically TypeError: Expected `adata.obs['day']` to be categorical with numeric categories, found `integer`.
> fix TypeError when running notebooks

- src/moscot/base/problems/problem.py
> changed tag literal in set_x, y, xy

- tests/problems/space/test_mapping_problem.py
btw once this and #633 are merged, think we can do a cleanup on branches, there are way too many that should be delted
> add geodesic test for y

- src/moscot/base/problems/birth_death.py
> expose scaling in estimate_marginals

- src/moscot/utils/_data/mouse_proliferation.txt
> removed duplicate

- src/moscot/plotting/_plotting.py
- src/moscot/plotting/_utils.py
- src/moscot/problems/generic/_mixins.py
- src/moscot/problems/time/_mixins.py
- tests/plotting/conftest.py
making plotting push/pull work with all problems
> mtp.push/pull for all problems

- src/moscot/datasets.py
> simulate cost matrices in simulate_data

- tests/_utils.py
- tests/conftest.py
- tests/problems/conftest.py
- tests/problems/generic/test_fgw_problem.py
- tests/problems/generic/test_gw_problem.py
- tests/problems/generic/test_sinkhorn_problem.py
- tests/problems/spatio_temporal/test_spatio_temporal_problem.py
- tests/problems/time/test_lineage_problem.py
- tests/problems/time/test_temporal_problem.py
Fixes https://github.com/theislab/moscot/issues/667. Added some tests that check if marginals are set.
> Added tests on passing marginals to `prepare`

- src/moscot/backends/ott/_utils.py
- src/moscot/problems/space/_mapping.py
- tests/problems/space/test_mapping_problem.py
This just checks whether `alpha=0` and in that case sets the quadratic attributes to `None`. 
Let me know what you think, I'm happy to add tests for this.
> Modify the SpatialMapping problem to enable solving a LinearProblem

- src/moscot/plotting/_utils.py
- src/moscot/problems/time/_mixins.py
> update check for categorical dtype

- src/moscot/utils/subset_policy.py
> fix value error in align

- docs/conf.py
> Added more links to ignore list
